### ISSUE TITLE
TypeError: Cannot call method "slice" of undefined.DetailsDismiss

### ISSUE THREAD

**Issue by datachand** [Xuefeng-Zhu/SheetSQL#1]
On 'CREATE TABLE', I am getting the error TypeError: Cannot call method "slice" of undefined.DetailsDismiss, and does not create a table

**Comment by Xuefeng-Zhu** [comment]
Can you provide the full command? Thanks.

**Comment by datachand** [comment]
'CREATE TABLE fun` that is all I gave. I was just testing it.

**Comment by Xuefeng-Zhu** [comment]
I have fixed the issue. thank you

**Comment by datachand** [comment]
Thank you... I ll check the working and close the bug
